#!/bin/bash 

# Quick check for the connexion

echo "=============================="

if ping -c 1 8.8.8.8 > /dev/null 2>&1; then 
	echo "The connexion is up" 
else 
	echo "No connexion"
fi
echo "=============================="
